[keyboard]
bindings = [
{ key = "V", mods = "Command", action = "Paste" },
{ key = "C", mods = "Command", action = "Copy" },
{ key = "F", mods = "Command", chars = "\u001bf" },
{ key = "B", mods = "Command", chars = "\u001bb" },
{ key = "D", mods = "Command", chars = "\u001bd" },
{ key = "A", mods = "Option", chars = "\u001b[1~" },
{ key = "E", mods = "Option", chars = "\u001b[4~" },
{ key = "K", mods = "Option", chars = "\u001b[0K" },
{ key = "U", mods = "Option", chars = "\u001b[1K" },
{ key = "Back", mods = "Command", chars = "\u001b\u007f" },
]

