set shell=bash\ --login
set nocp
set ru
set hls
syntax on
set backspace=indent,eol,start
set whichwrap=b,s,h,l,<,>,[,]
filetype plugin indent on

set sw=2
set ts=2
set et
set smarttab

if has('gui_running')
  set background=dark
  colorscheme desert
else
  " something for console Vim
endif

set cin
set cino=:0g0t0
set autoindent
set ic

set nu
nmap <F8> :set number! number?<CR>

nmap <F9> :set invpaste paste?<CR>
set pastetoggle=<F9>
set showmode

nmap gp :bp<cr>
nmap gn :bn<cr>
nmap gj <C-W>j
nmap gk <C-W>k
nmap gh <C-W>h
nmap gl <C-W>l

imap jj <Esc>

vnoremap p "_dP

map <Space> :

set clipboard=unnamed
